services:
  dbms:
    image: ${DB_IMAGE}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      TZ: ${OS_TIMEZONE}
    healthcheck:
      test: ["CMD-SHELL", "${DB_HEALTHCHECK}"]
      start_period: 5s
      start_interval: 1s
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - ${DB_PORT_HOST}:${DB_PORT_CONTAINER}
